name: Docker image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Docker Buildx Setup
      uses: docker/setup-buildx-action@v2
    - name: Push and upload
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME}}/tomcat-docker-compose:latest
          ${{ secrets.DOCKERHUB_USERNAME}}/tomcat-docker-compose:${{ github.sha}}
